#!/bin/bash

# Stop on first error
set -e;

BUILD_FAIL=0;

echo -e "\033[33m";
echo "	     _    _     _   _           ";
echo "	    | |  (_)_ _| |_(_)_ _  __ _ ";
echo "	    | |__| | ' \\  _| | ' \\/ _\` |";
echo "	    |____|_|_||_\\__|_|_||_\\__, |";
echo "	                           |___/ ";
echo -e "\033[0m";

eslint ./; true;
echo  -e "\033[38;5;35m" "Linting Successful!" "\033[0m";


echo -e "\033[33m";
echo "	      ___                _ _ _           ";
echo "	     / __|___ _ __  _ __(_) (_)_ _  __ _ ";
echo "	    | (__/ _ \\ '  \\| '_ \\ | | | ' \\/ _\` |";
echo "	     \\___\\___/_|_|_| .__/_|_|_|_||_\\__, |";
echo "	                   |_|             |___/ ";
echo -e "\033[0m";

# gulp clean && NODE_ENV=production gulp build;
# Make the build
npm run build


echo -e "\033[33m";
echo "         _   _       _ _     _____         _   _             ";
echo "        | | | |_ __ (_) |_  |_   _|__  ___| |_(_)_ __   __ _ ";
echo "        | | | | '_ \\| | __|   | |/ _ \\/ __| __| | '_ \\ / _\` |";
echo "        | |_| | | | | | |_    | |  __/\\__ \\ |_| | | | | (_| |";
echo "         \\___/|_| |_|_|\\__|   |_|\\___||___/\\__|_|_| |_|\\__, |";
echo "                                                       |___/ ";
echo -e "\033[0m";

npm run jsunit;
